### ISSUE TITLE
remove self from maintainers, wg membership

### ISSUE THREAD

**Issue by jlbutler** [opencontainers/certification#23]
I will continue to contribute to the runtime and image projects as a member of the technical community, but I need to bow out of certification work.

**Comment by RobDolinMS** [comment]
I'm sorry to hear this @jlbutler.  I hope everything is alright.  

Would you want to submit a PR to remove yourself from the [MAINTAINERS file](https://github.com/opencontainers/certification/blob/master/MAINTAINERS)?

**Comment by jlbutler** [comment]
Yes, working on that now. I'll still be around, just not in this project. Thanks.
